### ISSUE TITLE
Feature request: Support downloading from Github releases with version selection support

### ISSUE THREAD

**Issue by tamalsaha** [engineerd/configurator#10]
Thanks for this action. I wonder if this can be further extended to download binaries from GitHub releases with version selection. 

Here is my use-case. I have quite a few workflow files like this: https://github.com/stashed/CHANGELOG/blob/master/.github/workflows/release.yml#L21-L43

As you can see, I am downloading binaries from GitHub releases. The problem for me is that everytime I cut a new release, I have to update the files manually. What will be really helpful if I could use something like this:

```
    steps:
      - uses: engineerd/configurator@v0.0.2
        with:
          repo: appscodelabs/hugo-tools
          version: latest # v0.2.* etc semver constraint to automatically pick the version
          file: hugo-tools-linux-amd64
		  exe: hugo-tools
```

I am just making up this example. But the key point is that this action list Github releases and selects the one based on the version constraint and then installs the binary from that release.

Do you think this action can do that? If not, will you be willing to add support for something like this? Do you know any other action that can do this?

Thanks!

**Comment by radu-matei** [comment]
Hi, thanks for filing the issue,
this sounds like a great use case for this action!

A few questions related to your expected behavior:

- what should happen if the specified version doesn't exist?
- should the semver field accept tilde and caret ranges?
- should `latest` mean "latest semver release" or "latest chronological release"? (there are projects that support two or more major versions, with independent release cycles)
In the last two cases, regardless of the answer, the action would have to iterate through all the releases and select the appropriate version.


That being said, I am now looking at a few popular projects' releases, and I'm afraid I don't see any standard way of including binaries in releases. Here's what I mean:

- [Hugo releases](https://github.com/gohugoio/hugo/releases) contain the actual release binaries in the assets, so the in theory at least, the download URL could be programmatically obtained from the API. However, the asset object in the release doesn't have a platform field, so the correct file would have to be guessed somehow.

- [Helm releases](https://github.com/helm/helm/releases/tag/v3.3.0) (and a lot of other projects) only contain the actual binary URLs in the release notes body.

So it seems like at least a URL template would have to be provided (and hope the project keeps some consistency when it comes to URLs) - would that be acceptable?

**Comment by RichiCoder1** [comment]
@radu-matei I can answer some of the questions from my point of view.

> * what should happen if the specified version doesn't exist?

I'd personally expect the action to fail with an actionable error message.

> * should the semver field accept tilde and caret ranges?

That would be pretty excellent, especially if you could use some of the pre-existing versioning libs in the NPM community.

> * should latest mean "latest semver release" or "latest chronological release"? (there are projects that support two or more major versions, with independent release cycles)

I personally would assume latest chronological non-prerelease. If I wanted to pin to a specific version, I'd then opt provider a semver range.

> So it seems like at least a URL template would have to be provided (and hope the project keeps some consistency when it comes to URLs) - would that be acceptable?

That'd work well for me! Some flavor of mustache (or something else that's going to play nice with GitHub's own templating)

Something like this would be great:
```
    steps:
      - uses: engineerd/configurator
        with:
          repo: gohugoio/hugo
          version: latest 
          asset: hugo_{{version}}_Linux_64bit.tar.gz
		  path: hugo
```
