### ISSUE TITLE
Error: Not Found using urlTemplate

### ISSUE THREAD

**Issue by jbltx** [engineerd/configurator#18]
Hello,

I am able to use your action using the old `url` property, but when I try to use the `urlTemplate` I have an error. 

![image](https://user-images.githubusercontent.com/1284323/105433092-f5f63c80-5c26-11eb-9b10-f131cb951a9d.png)

Here's the step in the job : 
```yaml
    - uses: engineerd/configurator@v0.0.5
      with:
        name: docfx.exe
        pathInArchive: docfx.exe
        fromGitHubReleases: true
        includePrereleases: false
        version: latest
        repo: https://github.com/dotnet/docfx.git
        urlTemplate: https://github.com/dotnet/docfx/releases/download/{{version}}/docfx.zip
        token: ${{ secrets.GITHUB_TOKEN }}
```

Also I know it won't work anyway because there's no support for the `directory` property yet, but I would know why I got this error. Thank you!
