### ISSUE TITLE
Input parameters based on matrix value

### ISSUE THREAD

**Issue by radu-matei** [engineerd/configurator#2]
Since this is a cross-platform action, and GitHub Actions supports [a build matrix](https://help.github.com/en/articles/configuring-a-workflow#configuring-a-build-matrix), it would be really nice to be able to set all action parameters based on the OS from the matrix. 

However, I'm not sure if it is possible to have a set of inputs enabled only for a specific OS (rather than running all possible combinations of inputs from the matrix).

**Comment by radu-matei** [comment]
This is exactly what I was looking for:

```
jobs:
  configurator:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {os: "ubuntu-latest", url: "https://get.helm.sh/helm-v3.0.0-beta.3-linux-amd64.tar.gz", name: "hb3", pathInArchive: "linux-amd64/helm" }
        - {os: "windows-latest", url: "https://get.helm.sh/helm-v3.0.0-beta.3-windows-amd64.zip", name: "hb3.exe", pathInArchive: "windows-amd64/helm.exe" }
    steps:
      - uses: engineerd/configurator@v0.0.1
        with:
          name: ${{ matrix.config.name }}
          url: ${{ matrix.config.url }}
          pathInArchive: ${{ matrix.config.pathInArchive }}
      - name: Testing
        run: |
          hb3 --help
```
