### ISSUE TITLE
Infer some values for Github Release

### ISSUE THREAD

**Issue by RichiCoder1** [engineerd/configurator#29]
Having used this action a few times now, I think there's some possibility to make the action a bit less boilerplate-y.

Specifically, if the user specifies a `urlTemplate` that matches `^https:\/\/github\.com\/(?<repo>.*\/.*)\/releases\/download\/`, infer the following:
```
fromGithubReleases: true
repo: <repo from regex>
version: latest
```

So that this:
```yaml
      - uses: engineerd/configurator@v0.0.8
        with:
          name: "kind"
          fromGitHubReleases: "true"
          repo: "kubernetes-sigs/kind"
          urlTemplate: "https://github.com/kubernetes-sigs/kind/releases/download/{{version}}/kind-linux-amd64"
          version: "latest"
          token: ${{ secrets.GITHUB_TOKEN }}
```

would become this:

```yaml
      - uses: engineerd/configurator@v0.0.8
        with:
          name: "kind"
          urlTemplate: "https://github.com/kubernetes-sigs/kind/releases/download/{{version}}/kind-linux-amd64"
          token: ${{ secrets.GITHUB_TOKEN }}
```
