### ISSUE TITLE
executable tool with dependencies

### ISSUE THREAD

**Issue by xls** [engineerd/configurator#32]
When executing the tool defined in PathInArchive, its dependent binary can't be loaded and error out.
Is this by design? I Briefly looked at the code but would including binary path to PATH environment be effective instead of move?

**Comment by i2van** [comment]
`pathInArchive: "*.*"` does not work, it is also mandatory when used with archive.

I extracted each file separately:

```yaml
      - uses: engineerd/configurator@v0.0.10
        with:
          name: "LPRun8-x64.exe"
          url: "https://www.linqpad.net/GetFile.aspx?preview+LINQPad8-Beta.zip"
          pathInArchive: "LPRun8-x64.exe"
      - uses: engineerd/configurator@v0.0.10
        with:
          name: "LINQPad.Runtime.dll"
          url: "https://www.linqpad.net/GetFile.aspx?preview+LINQPad8-Beta.zip"
          pathInArchive: "LINQPad.Runtime.dll"
```
