### ISSUE TITLE
Allow for different bin folder executables

### ISSUE THREAD

**Issue by palfrey** [engineerd/configurator#38]
I was trying to do
```
      - uses: engineerd/configurator@v0.0.8
        with:
          name: /home/runner/.cargo/bin/cargo-binstall
          url: https://github.com/ryankurte/cargo-binstall/releases/download/v0.11.1/cargo-binstall-x86_64-unknown-linux-musl.tgz
          pathInArchive: cargo-binstall
```

and it installed to `/home/runner/configurator/bin/home/runner/.cargo/bin/cargo-binstall` not the folder I expected!
